Fix strip function for Windows executables.

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -1482,49 +1482,129 @@ run_package() {
 	run_function_safe "$pkgfunc"
 }
 
-build_id() {
-	LANG=C readelf -n $1 | sed -n '/Build ID/ { s/.*: //p; q; }'
-}
-
 strip_file() {
 	local binary=$1; shift
 
 	if check_option "debug" "y"; then
-		local bid=$(build_id "$binary")
-
-		# has this file already been stripped
-		if [[ -n "$bid" ]]; then
-			if [[ -f "$dbgdir/.build_id/${bid:0:2}/${bid:2}.debug" ]]; then
-				return
-			fi
-		elif [[ -f "$dbgdir/$binary.debug" ]]; then
-			return
-		fi
 
 		mkdir -p "$dbgdir/${binary%/*}"
-		objcopy --only-keep-debug "$binary" "$dbgdir/$binary.debug"
-		objcopy --add-gnu-debuglink="$dbgdir/${binary#/}.debug" "$binary"
 
-		# create any needed hardlinks
-		while read -rd '' file ; do
-			if [[ "${binary}" -ef "${file}" && ! -f "$dbgdir/${file}.debug" ]]; then
-				mkdir -p "$dbgdir/${file%/*}"
-				ln "$dbgdir/${binary}.debug" "$dbgdir/${file}.debug"
-			fi
-		done < <(find . -type f -perm -u+w -print0 2>/dev/null)
-
-		if [[ -n "$bid" ]]; then
-			local target
-			mkdir -p "$dbgdir/.build_id/${bid:0:2}"
-
-			target="../../../../../${binary#./}"
-			target="${target/..\/..\/usr\/lib\/}"
-			target="${target/..\/usr\/}"
-			ln -s "$target" "$dbgdir/.build_id/${bid:0:2}/${bid:2}"
-
-			target="../../${binary#./}.debug"
-			ln -s "$target" "$dbgdir/.build_id/${bid:0:2}/${bid:2}.debug"
+		# assure this is actually a binary object
+		if [ "$(head -c 2 "${binary}")" = '#!' ]
+		then
+			# sometimes .exe will be appended where it does not belong
+			case "${binary}" in
+			usr/lib/hevea/*.exe) ;;
+			*.exe)	mv "${binary}" "${binary%.exe}" ;;
+			esac
+			continue
 		fi
+
+		# OCaml bytecode must not be stripped
+		# Magic number is at end of file:
+		# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=256900#74
+		# http://cygwin.com/ml/cygwin-apps/2010-10/msg00057.html
+		case $(tail -c 12 "${binary}") in
+			Caml1999X0[0-9][0-9])  continue ;;
+		esac
+
+		# Perl Archive (PAR) binaries must not be stripped
+		# https://rt.cpan.org/Public/Bug/Display.html?id=18536
+		# http://cygwin.com/ml/cygwin-apps/2012-07/msg00088.html
+		case $(tail -c 8 "${binary}" | tr '\012' '%') in
+			%PAR\.pm%)  continue ;;
+		esac
+
+		case "${binary}" in
+		usr/*/lib*/lib*|usr/*/sys-root/*)
+			tmpvar="${binary#usr/}"
+			arch_tree="${tmpvar%%/*}"
+			;;
+		usr/lib/gcc/*/lib*)
+			tmpvar="${binary#usr/lib/gcc/}"
+			arch_tree="${tmpvar%%/*}"
+			;;
+		esac
+
+		# Static libraries should not be fully stripped, but we can
+		# still provide split debuginfo if desired
+		case "${binary}" in *.a)
+			#if defined _CYGPORT_RESTRICT_debuginfo_
+			#then
+			#	echo "        ${binary}";
+			#	objcopy --strip-debug "${binary}";
+			#else
+				objdump -dl "${binary}" 2>/dev/null | grep /usr/src/debug | sed -e 's/:[0-9]*$//g' | sort -u >> ${dbgdir}/$binary.debug;
+			#fi
+			continue
+			;;
+		esac
+
+		# Mono assemblies must not be stripped, but remove .mdb debug symbols,
+		# and make them non-executable so they're not launched by MS .NET
+		if file -b "${binary}" 2>&1 | grep -q "Mono/\.Net assembly"
+		then
+			chmod 0644 "${binary}"
+			rm -f "${binary}.mdb"
+			continue
+		fi
+
+		# check for DLLs with low-address manual ImageBase, either
+		# due to -Wl,--image-base, or BASE directive in .def file;
+		case ${CHOST} in
+		x86_64-*-msys*|x86_64-*-cygwin*)
+			case "${binary##*/}" in
+			cygwin1.dll|msys-2.0.dll|cyglsa64.dll) ;;
+			*.dll|*.so|*.oct|*.cmxs)
+				if objdump -p "${binary}" | sed -ne '/^ImageBase/s/.*\t/0x/gp' | gawk '{ exit (strtonum($1) <= 0x400000000 ? 0 : 1) }'
+				then
+					warning "${binary} was not linked with -Wl,--enable-auto-image-base"
+				fi
+			esac
+		esac
+
+		# check for .exe from non-automake Makefile which install(1) didn't fix
+		# strip(1) used to take care of this, but not anymore
+		case ${CHOST} in
+		*-*-cygwin*|*-*-mingw*|*-*-msys*)
+			case "${binary##*/}" in
+			*.dll|*.exe|*.sfx|*.so|*.so.[0-9]*|*.oct|*.cmxs) ;;
+			# make sure this isn't some oddly named DLL
+			*)	if objdump -f "${binary}" | grep -Eq '^start address 0x(0000000[01])?00401[0-9a-e][0-9a-e]0'
+				then
+					mv "${binary}" "${binary}.exe"
+					binary+=.exe
+				fi ;;
+			esac
+			;;
+		esac
+
+		echo "        ${binary}";
+		chmod 0755 "${binary}";
+
+		#if defined _CYGPORT_RESTRICT_debuginfo_
+		#then
+		#	objcopy --strip-all "${binary}";
+		#else
+			dbg="/usr/lib/debug/${binary}.debug";
+
+			lines=$(objdump -dl "${binary}" 2>/dev/null | grep /usr/src/debug/${PF}/ | sed -e 's/:[0-9]*$//g' | sort -u | tee -a ${dbgdir}/${binary}.debug.out | wc -l);
+
+			if (( lines == 0 ))
+			then
+				objcopy --strip-all "${binary}";
+				continue;
+			fi
+
+			# --add-gnu-debuglink will fail if .gnu_debuglink section
+			# already exists, e.g. binutils, which uses hardlinks,
+			# or cygwin which creates a custom .dbg file
+			if ! objdump -h "${binary}" | grep -q '\.gnu_deb'
+			then
+				objcopy --long-section-names enable --add-gnu-debuglink=/dev/null --only-keep-debug "${binary}" "${dbgdir}/$binary.debug";
+				objcopy --strip-all "${binary}";
+				objcopy --long-section-names enable --add-gnu-debuglink="${dbgdir}/${binary#/}.debug" "${binary}" 2>/dev/null;
+			fi
 	fi
 
 	strip $@ "$binary"
@@ -1622,8 +1702,17 @@ tidy_install() {
 		fi
 
 		local binary strip_flags
-		find . -type f -perm -u+w -print0 2>/dev/null | while read -rd '' binary ; do
+		# *.so: Apache2 modules, OCaml stublibs, Ruby modules
+		# *.oct: Octave modules
+		# *.cmxs: OCaml natdynlink modules: http://gallium.inria.fr/~frisch/ndl.txt
+		find * -type f ! -name '*.dll.a' ! -name '*.lib' \
+			-a \( -name '*.a' -o -name '*.dll' -o -name '*.exe' -o -name '*.so' -o -name '*.so.*' -o -name '*.oct' -o -name '*.cmxs' \) -print0 \
+			-o -type f -executable ! -name '*.dll' ! -name '*.exe' ! -name '*.so' ! -name '*.so.[0-9]*' ! -name '*.oct' ! -name '*.cmxs' ! -name '*.a' ! -name '*.la' ! -name '*.lib' ! -name '*.exe.manifest' ! -name '*.exe.config' ! -name '*.dll.config' ! -name '*.mdb' ! -name '*-config' ! -name '*.csh' ! -name '*.sh' ! -name '*.pl' ! -name '*.pm' ! -name '*.py' ! -name '*.rb' ! -name '*.tcl' -print0 | \
+		while read -d $'\0' binary
+		do
 			case "$(file -bi "$binary")" in
+				*application/x-dosexec*) # Windows executables and dlls
+					strip_flags="$STRIP_SHARED";;
 				*application/x-sharedlib*)  # Libraries (.so)
 					strip_flags="$STRIP_SHARED";;
 				*application/x-archive*)    # Libraries (.a)
