Force to use MSYS utilities if MINGW analogs present in PATH.

diff --git a/scripts/repo-add.sh.in b/scripts/repo-add.sh.in
--- a/scripts/repo-add.sh.in
+++ b/scripts/repo-add.sh.in
@@ -50,49 +50,49 @@ usage() {
 	cmd=${0##*/}
 	printf -- "%s (pacman) %s\n\n" "$cmd" "$myver"
 	if [[ $cmd == "repo-add" ]] ; then
-		printf -- "$(gettext "Usage: repo-add [options] <path-to-db> <package|delta> ...\n")"
+		printf -- "$(/bin/gettext "Usage: repo-add [options] <path-to-db> <package|delta> ...\n")"
 		printf -- "\n"
-		printf -- "$(gettext "\
+		printf -- "$(/bin/gettext "\
 repo-add will update a package database by reading a package file.\n\
 Multiple packages to add can be specified on the command line.\n")"
 		printf -- "\n"
-		printf -- "$(gettext "Options:\n")"
-		printf -- "$(gettext "  -d, --delta       generate and add delta for package update\n")"
-		printf -- "$(gettext "  -n, --new         only add packages that are not already in the database\n")"
-		printf -- "$(gettext "  -R, --remove      remove package file from disk when updating database entry\n")"
-		printf -- "$(gettext "  -f, --files       update database's file list\n")"
+		printf -- "$(/bin/gettext "Options:\n")"
+		printf -- "$(/bin/gettext "  -d, --delta       generate and add delta for package update\n")"
+		printf -- "$(/bin/gettext "  -n, --new         only add packages that are not already in the database\n")"
+		printf -- "$(/bin/gettext "  -R, --remove      remove package file from disk when updating database entry\n")"
+		printf -- "$(/bin/gettext "  -f, --files       update database's file list\n")"
 	elif [[ $cmd == "repo-remove" ]] ; then
-		printf -- "$(gettext "Usage: repo-remove [options] <path-to-db> <packagename|delta> ...\n")"
+		printf -- "$(/bin/gettext "Usage: repo-remove [options] <path-to-db> <packagename|delta> ...\n")"
 		printf -- "\n"
-		printf -- "$(gettext "\
+		printf -- "$(/bin/gettext "\
 repo-remove will update a package database by removing the package name\n\
 specified on the command line from the given repo database. Multiple\n\
 packages to remove can be specified on the command line.\n")"
 		printf -- "\n"
-		printf -- "$(gettext "Options:\n")"
+		printf -- "$(/bin/gettext "Options:\n")"
 	else
-		printf -- "$(gettext "Please move along, there is nothing to see here.\n")"
+		printf -- "$(/bin/gettext "Please move along, there is nothing to see here.\n")"
 		return
 	fi
-	printf -- "$(gettext "  --nocolor         turn off color in output\n")"
-	printf -- "$(gettext "  -q, --quiet       minimize output\n")"
-	printf -- "$(gettext "  -s, --sign        sign database with GnuPG after update\n")"
-	printf -- "$(gettext "  -k, --key <key>   use the specified key to sign the database\n")"
-	printf -- "$(gettext "  -v, --verify      verify database's signature before update\n")"
-	printf -- "$(gettext "\n\
+	printf -- "$(/bin/gettext "  --nocolor         turn off color in output\n")"
+	printf -- "$(/bin/gettext "  -q, --quiet       minimize output\n")"
+	printf -- "$(/bin/gettext "  -s, --sign        sign database with GnuPG after update\n")"
+	printf -- "$(/bin/gettext "  -k, --key <key>   use the specified key to sign the database\n")"
+	printf -- "$(/bin/gettext "  -v, --verify      verify database's signature before update\n")"
+	printf -- "$(/bin/gettext "\n\
 See %s(8) for more details and descriptions of the available options.\n")" $cmd
 	printf "\n"
 	if [[ $cmd == "repo-add" ]] ; then
-		printf -- "$(gettext "Example:  repo-add /path/to/repo.db.tar.gz pacman-3.0.0-1-i686.pkg.tar.gz\n")"
+		printf -- "$(/bin/gettext "Example:  repo-add /path/to/repo.db.tar.gz pacman-3.0.0-1-i686.pkg.tar.gz\n")"
 	elif [[ $cmd == "repo-remove" ]] ; then
-		printf -- "$(gettext "Example:  repo-remove /path/to/repo.db.tar.gz kernel26\n")"
+		printf -- "$(/bin/gettext "Example:  repo-remove /path/to/repo.db.tar.gz kernel26\n")"
 	fi
 }
 
 version() {
 	cmd=${0##*/}
 	printf "%s (pacman) %s\n\n" "$cmd" "$myver"
-	printf -- "$(gettext "\
+	printf -- "$(/bin/gettext "\
 Copyright (c) 2006-2013 Pacman Development Team <pacman-dev@archlinux.org>\n\n\
 This is free software; see the source for copying conditions.\n\
 There is NO WARRANTY, to the extent permitted by law.\n")"
@@ -140,7 +140,7 @@ db_write_delta() {
 
 	pkgentry=$(find_pkgentry "$pkgname")
 	if [[ -z $pkgentry ]]; then
-		error "$(gettext "No database entry for package '%s'.")" "$pkgname"
+		error "$(/bin/gettext "No database entry for package '%s'.")" "$pkgname"
 		return 1
 	fi
 	deltas=$pkgentry/deltas
@@ -148,7 +148,7 @@ db_write_delta() {
 		echo -e "%DELTAS%" >"$deltas"
 	fi
 	# get md5sum and compressed size of package
-	md5sum=$(openssl dgst -md5 "$deltafile")
+	md5sum=$(/bin/openssl dgst -md5 "$deltafile")
 	md5sum=${md5sum##* }
 	csize=$(@SIZECMD@ -L "$deltafile")
 
@@ -158,7 +158,7 @@ db_write_delta() {
 	if grep -q "$oldfile.*$newfile" "$deltas"; then
 		sed -i.backup "/$oldfile.*$newfile/d" "$deltas" && rm -f "$deltas.backup"
 	fi
-	msg2 "$(gettext "Adding 'deltas' entry : %s -> %s")" "$oldfile" "$newfile"
+	msg2 "$(/bin/gettext "Adding 'deltas' entry : %s -> %s")" "$oldfile" "$newfile"
 	echo "${deltafile##*/} $md5sum $csize $oldfile $newfile" >> "$deltas"
 
 	return 0
@@ -181,10 +181,10 @@ db_remove_delta() {
 	fi
 	if grep -q "$filename" "$deltas"; then
 		sed -i.backup "/$filename/d" "$deltas" && rm -f "$deltas.backup"
-		msg2 "$(gettext "Removing existing entry '%s'...")" "$filename"
+		msg2 "$(/bin/gettext "Removing existing entry '%s'...")" "$filename"
 		# empty deltas file contains only "%DELTAS%"
 		if (( $(wc -l < "$deltas") == 1 )); then
-			msg2 "$(gettext "Removing empty deltas file ...")"
+			msg2 "$(/bin/gettext "Removing empty deltas file ...")"
 			rm "$deltas"
 		fi
 		return 0
@@ -195,7 +195,7 @@ db_remove_delta() {
 
 check_gpg() {
 	if ! type -p gpg >/dev/null; then
-		error "$(gettext "Cannot find the gpg binary! Is GnuPG installed?")"
+		error "$(/bin/gettext "Cannot find the gpg binary! Is GnuPG installed?")"
 		exit 1 # $E_MISSING_PROGRAM
 	fi
 }
@@ -205,18 +205,18 @@ create_signature() {
 	(( ! SIGN )) && return
 	local dbfile=$1
 	local ret=0
-	msg "$(gettext "Signing database...")"
+	msg "$(/bin/gettext "Signing database...")"
 
 	local SIGNWITHKEY=""
 	if [[ -n $GPGKEY ]]; then
 		SIGNWITHKEY="-u ${GPGKEY}"
 	fi
-	gpg --detach-sign --use-agent ${SIGNWITHKEY} "$dbfile" &>/dev/null || ret=$?
+	/bin/gpg --detach-sign --use-agent ${SIGNWITHKEY} "$dbfile" &>/dev/null || ret=$?
 
 	if (( ! ret )); then
-		msg2 "$(gettext "Created signature file '%s'")" "${dbfile##*/.tmp.}.sig"
+		msg2 "$(/bin/gettext "Created signature file '%s'")" "${dbfile##*/.tmp.}.sig"
 	else
-		warning "$(gettext "Failed to sign package database.")"
+		warning "$(/bin/gettext "Failed to sign package database.")"
 	fi
 }
 
@@ -225,17 +225,17 @@ verify_signature() {
 	(( ! VERIFY )) && return
 	local dbfile=$1
 	local ret=0
-	msg "$(gettext "Verifying database signature...")"
+	msg "$(/bin/gettext "Verifying database signature...")"
 
 	if [[ ! -f $dbfile.sig ]]; then
-		warning "$(gettext "No existing signature found, skipping verification.")"
+		warning "$(/bin/gettext "No existing signature found, skipping verification.")"
 		return
 	fi
-	gpg --verify "$dbfile.sig" || ret=$?
+	/bin/gpg --verify "$dbfile.sig" || ret=$?
 	if (( ! ret )); then
-		msg2 "$(gettext "Database signature file verified.")"
+		msg2 "$(/bin/gettext "Database signature file verified.")"
 	else
-		error "$(gettext "Database signature was NOT valid!")"
+		error "$(/bin/gettext "Database signature was NOT valid!")"
 		exit 1
 	fi
 }
@@ -286,16 +286,16 @@ db_write_entry() {
 			makedepend) _makedepends+=("$makedepend") ;;
 			checkdepend) _checkdepends+=("$checkdepend") ;;
 		esac
-	done< <(bsdtar -xOqf "$pkgfile" .PKGINFO)
+	done< <(/bin/bsdtar -xOqf "$pkgfile" .PKGINFO)
 
 	# ensure $pkgname and $pkgver variables were found
 	if [[ -z $pkgname || -z $pkgver ]]; then
-		error "$(gettext "Invalid package file '%s'.")" "$pkgfile"
+		error "$(/bin/gettext "Invalid package file '%s'.")" "$pkgfile"
 		return 1
 	fi
 
 	if [[ -d $tmpdir/tree/$pkgname-$pkgver ]]; then
-		warning "$(gettext "An entry for '%s' already existed")" "$pkgname-$pkgver"
+		warning "$(/bin/gettext "An entry for '%s' already existed")" "$pkgname-$pkgver"
 		if (( ONLYADDNEW )); then
 			return 0;
 		fi
@@ -312,7 +312,7 @@ db_write_entry() {
 			if [[ -n $pkgentry ]]; then
 				local oldfilename="$(sed -n '/^%FILENAME%$/ {n;p;q;}' "$pkgentry/desc")"
 				local oldfile="$(dirname "$1")/$oldfilename"
-				msg2 "$(gettext "Removing existing package '%s'")" "$oldfilename"
+				msg2 "$(/bin/gettext "Removing existing package '%s'")" "$oldfilename"
 				rm -f ${oldfile} ${oldfile}.sig
 			fi
 		fi
@@ -322,20 +322,20 @@ db_write_entry() {
 	if [[ -f "$pkgfile.sig" ]]; then
 		pgpsigsize=$(@SIZECMD@ -L "$pkgfile.sig")
 		if (( pgpsigsize > 16384 )); then
-			error "$(gettext "Invalid package signature file '%s'.")" "$pkgfile.sig"
+			error "$(/bin/gettext "Invalid package signature file '%s'.")" "$pkgfile.sig"
 			return 1
 		fi
-		msg2 "$(gettext "Adding package signature...")"
-		pgpsig=$(openssl base64 -in "$pkgfile.sig" | tr -d '\n')
+		msg2 "$(/bin/gettext "Adding package signature...")"
+		pgpsig=$(/bin/openssl base64 -in "$pkgfile.sig" | tr -d '\n')
 	fi
 
 	csize=$(@SIZECMD@ -L "$pkgfile")
 
 	# compute checksums
-	msg2 "$(gettext "Computing checksums...")"
-	md5sum=$(openssl dgst -md5 "$pkgfile")
+	msg2 "$(/bin/gettext "Computing checksums...")"
+	md5sum=$(/bin/openssl dgst -md5 "$pkgfile")
 	md5sum=${md5sum##* }
-	sha256sum=$(openssl dgst -sha256 "$pkgfile")
+	sha256sum=$(/bin/openssl dgst -sha256 "$pkgfile")
 	sha256sum=${sha256sum##* }
 
 	# remove an existing entry if it exists, ignore failures
@@ -350,7 +350,7 @@ db_write_entry() {
 	[[ -f ../$pkgname.deltas ]] && mv "../$pkgname.deltas" deltas
 
 	# create desc entry
-	msg2 "$(gettext "Creating '%s' db entry...")" 'desc'
+	msg2 "$(/bin/gettext "Creating '%s' db entry...")" 'desc'
 	{
 		format_entry "FILENAME"  "${1##*/}"
 		format_entry "NAME"      "$pkgname"
@@ -377,7 +377,7 @@ db_write_entry() {
 	} >'desc'
 
 	# create depends entry
-	msg2 "$(gettext "Creating '%s' db entry...")" 'depends'
+	msg2 "$(/bin/gettext "Creating '%s' db entry...")" 'depends'
 	{
 		format_entry "DEPENDS" "${_depends[@]}"
 		format_entry "CONFLICTS" "${_conflicts[@]}"
@@ -392,10 +392,10 @@ db_write_entry() {
 
 	# create files file if wanted
 	if (( WITHFILES )); then
-		msg2 "$(gettext "Creating '%s' db entry...")" 'files'
+		msg2 "$(/bin/gettext "Creating '%s' db entry...")" 'files'
 		local files_path="$tmpdir/tree/$pkgname-$pkgver/files"
 		echo "%FILES%" >"$files_path"
-		bsdtar --exclude='^.*' -tf "$pkgfile" >>"$files_path"
+		/bin/bsdtar --exclude='^.*' -tf "$pkgfile" >>"$files_path"
 	fi
 
 	# create a delta file
@@ -407,7 +407,7 @@ db_write_entry() {
 					db_write_delta "$delta"
 				fi
 			else
-				warning "$(gettext "Old package file not found: %s")" "$oldfilename"
+				warning "$(/bin/gettext "Old package file not found: %s")" "$oldfilename"
 			fi
 		fi
 	fi
@@ -426,7 +426,7 @@ db_remove_entry() {
 		if [[ -f $pkgentry/deltas ]]; then
 			mv "$pkgentry/deltas" "$tmpdir/tree/$pkgname.deltas"
 		fi
-		msg2 "$(gettext "Removing existing entry '%s'...")" \
+		msg2 "$(/bin/gettext "Removing existing entry '%s'...")" \
 		"${pkgentry##*/}"
 		rm -rf "$pkgentry"
 		pkgentry=$(find_pkgentry "$pkgname")
@@ -446,7 +446,7 @@ elephant() {
 		                 "ZL9JFFZeAa0a2+lKjL2anpYfV+0Zx9LJ+/MC8nRayuDlSNy2rfAPibOzsiWHL0jL" \
 		                 "SsjFAQAA"
 		;;
-	esac | openssl base64 -d | gzip -d
+	esac | /bin/openssl base64 -d | /bin/gzip -d
 }
 
 check_repo_db() {
@@ -456,7 +456,7 @@ check_repo_db() {
 	repodir=${LOCKFILE%/*}/
 
 	if [[ ! -d $repodir ]]; then
-		error "$(gettext "%s does not exist or is not a directory.")" "$repodir"
+		error "$(/bin/gettext "%s does not exist or is not a directory.")" "$repodir"
 		exit 1
 	fi
 
@@ -464,34 +464,34 @@ check_repo_db() {
 	if ( set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
 		CLEAN_LOCK=1
 	else
-		error "$(gettext "Failed to acquire lockfile: %s.")" "$LOCKFILE"
-		[[ -f $LOCKFILE ]] && error "$(gettext "Held by process %s")" "$(cat "$LOCKFILE")"
+		error "$(/bin/gettext "Failed to acquire lockfile: %s.")" "$LOCKFILE"
+		[[ -f $LOCKFILE ]] && error "$(/bin/gettext "Held by process %s")" "$(cat "$LOCKFILE")"
 		exit 1
 	fi
 
 	if [[ -f $REPO_DB_FILE ]]; then
 		# there are two situations we can have here- a DB with some entries,
 		# or a DB with no contents at all.
-		if ! bsdtar -tqf "$REPO_DB_FILE" '*/desc' >/dev/null 2>&1; then
+		if ! /bin/bsdtar -tqf "$REPO_DB_FILE" '*/desc' >/dev/null 2>&1; then
 			# check empty case
-			if [[ -n $(bsdtar -tqf "$REPO_DB_FILE" '*' 2>/dev/null) ]]; then
-				error "$(gettext "Repository file '%s' is not a proper pacman database.")" "$REPO_DB_FILE"
+			if [[ -n $(/bin/bsdtar -tqf "$REPO_DB_FILE" '*' 2>/dev/null) ]]; then
+				error "$(/bin/gettext "Repository file '%s' is not a proper pacman database.")" "$REPO_DB_FILE"
 				exit 1
 			fi
 		fi
 		verify_signature "$REPO_DB_FILE"
-		msg "$(gettext "Extracting database to a temporary location...")"
-		bsdtar -xf "$REPO_DB_FILE" -C "$tmpdir/tree"
+		msg "$(/bin/gettext "Extracting database to a temporary location...")"
+		/bin/bsdtar -xf "$REPO_DB_FILE" -C "$tmpdir/tree"
 	else
 		case $cmd in
 			repo-remove)
-			error "$(gettext "Repository file '%s' was not found.")" "$REPO_DB_FILE"
+			error "$(/bin/gettext "Repository file '%s' was not found.")" "$REPO_DB_FILE"
 			exit 1
 			;;
 			repo-add)
 			# check if the file can be created (write permission, directory existence, etc)
 			if ! touch "$REPO_DB_FILE"; then
-				error "$(gettext "Repository file '%s' could not be created.")" "$REPO_DB_FILE"
+				error "$(/bin/gettext "Repository file '%s' could not be created.")" "$REPO_DB_FILE"
 				exit 1
 			fi
 			rm -f "$REPO_DB_FILE"
@@ -502,15 +502,15 @@ check_repo_db() {
 
 add() {
 	if [[ ! -f $1 ]]; then
-		error "$(gettext "File '%s' not found.")" "$1"
+		error "$(/bin/gettext "File '%s' not found.")" "$1"
 		return 1
 	fi
 
 	if [[ ${1##*.} == "delta" ]]; then
 		deltafile=$1
-		msg "$(gettext "Adding delta '%s'")" "$deltafile"
+		msg "$(/bin/gettext "Adding delta '%s'")" "$deltafile"
 		if ! type xdelta3 &>/dev/null; then
-			error "$(gettext "Cannot find the xdelta3 binary! Is xdelta3 installed?")"
+			error "$(/bin/gettext "Cannot find the xdelta3 binary! Is xdelta3 installed?")"
 			exit 1
 		fi
 		if db_write_delta "$deltafile"; then
@@ -521,12 +521,12 @@ add() {
 	fi
 
 	pkgfile=$1
-	if ! bsdtar -tqf "$pkgfile" .PKGINFO >/dev/null 2>&1; then
-		error "$(gettext "'%s' is not a package file, skipping")" "$pkgfile"
+	if ! /bin/bsdtar -tqf "$pkgfile" .PKGINFO >/dev/null 2>&1; then
+		error "$(/bin/gettext "'%s' is not a package file, skipping")" "$pkgfile"
 		return 1
 	fi
 
-	msg "$(gettext "Adding package '%s'")" "$pkgfile"
+	msg "$(/bin/gettext "Adding package '%s'")" "$pkgfile"
 
 	db_write_entry "$pkgfile"
 }
@@ -534,23 +534,23 @@ add() {
 remove() {
 	if [[ ${1##*.} == "delta" ]]; then
 		deltafile=$1
-		msg "$(gettext "Searching for delta '%s'...")" "$deltafile"
+		msg "$(/bin/gettext "Searching for delta '%s'...")" "$deltafile"
 		if db_remove_delta "$deltafile"; then
 			return 0
 		else
-			error "$(gettext "Delta matching '%s' not found.")" "$deltafile"
+			error "$(/bin/gettext "Delta matching '%s' not found.")" "$deltafile"
 			return 1
 		fi
 	fi
 
 	pkgname=$1
-	msg "$(gettext "Searching for package '%s'...")" "$pkgname"
+	msg "$(/bin/gettext "Searching for package '%s'...")" "$pkgname"
 
 	if db_remove_entry "$pkgname"; then
 		rm -f "$tmpdir/tree/$pkgname.deltas"
 		return 0
 	else
-		error "$(gettext "Package matching '%s' not found.")" "$pkgname"
+		error "$(/bin/gettext "Package matching '%s' not found.")" "$pkgname"
 		return 1
 	fi
 }
@@ -598,21 +598,21 @@ if [[ $cmd == "repo-elephant" ]]; then
 fi
 
 if [[ $cmd != "repo-add" && $cmd != "repo-remove" ]]; then
-	error "$(gettext "Invalid command name '%s' specified.")" "$cmd"
+	error "$(/bin/gettext "Invalid command name '%s' specified.")" "$cmd"
 	exit 1
 fi
 
 tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/repo-tools.XXXXXXXXXX") || (\
-	error "$(gettext "Cannot create temp directory for database building.")"; \
+	error "$(/bin/gettext "Cannot create temp directory for database building.")"; \
 	exit 1)
 mkdir "$tmpdir/tree"
 
 trap 'clean_up' EXIT
 for signal in TERM HUP QUIT; do
-	trap "trap_exit \"$(gettext "%s signal caught. Exiting...")\" \"$signal\"" "$signal"
+	trap "trap_exit \"$(/bin/gettext "%s signal caught. Exiting...")\" \"$signal\"" "$signal"
 done
-trap 'trap_exit "$(gettext "Aborted by user! Exiting...")"' INT
-trap 'trap_exit "$(gettext "An unknown error has occurred. Exiting...")"' ERR
+trap 'trap_exit "$(/bin/gettext "Aborted by user! Exiting...")"' INT
+trap 'trap_exit "$(/bin/gettext "An unknown error has occurred. Exiting...")"' ERR
 
 declare -a args
 success=0
@@ -628,11 +628,11 @@ while (( $# )); do
 		-s|--sign)
 			check_gpg
 			SIGN=1
-			if ! gpg --list-key ${GPGKEY} &>/dev/null; then
+			if ! /bin/gpg --list-key ${GPGKEY} &>/dev/null; then
 				if [[ ! -z $GPGKEY ]]; then
-					error "$(gettext "The key ${GPGKEY} does not exist in your keyring.")"
+					error "$(/bin/gettext "The key ${GPGKEY} does not exist in your keyring.")"
 				else
-					error "$(gettext "There is no key in your keyring.")"
+					error "$(/bin/gettext "There is no key in your keyring.")"
 				fi
 				exit 1
 			fi
@@ -641,8 +641,8 @@ while (( $# )); do
 			check_gpg
 			shift
 			GPGKEY=$1
-			if ! gpg --list-key ${GPGKEY} &>/dev/null; then
-				error "$(gettext "The key ${GPGKEY} does not exist in your keyring.")"
+			if ! /bin/gpg --list-key ${GPGKEY} &>/dev/null; then
+				error "$(/bin/gettext "The key ${GPGKEY} does not exist in your keyring.")"
 				exit 1
 			fi
 			;;
@@ -683,7 +683,7 @@ done
 
 # if at least one operation was a success, re-zip database
 if (( success )); then
-	msg "$(gettext "Creating updated database file '%s'")" "$REPO_DB_FILE"
+	msg "$(/bin/gettext "Creating updated database file '%s'")" "$REPO_DB_FILE"
 
 	TAR_OPT=$(verify_repo_extension "$REPO_DB_FILE")
 	# $LOCKFILE is already guaranteed to be absolute so this is safe
@@ -694,11 +694,11 @@ if (( success )); then
 
 	pushd "$tmpdir/tree" >/dev/null
 	if ( shopt -s nullglob; files=(*); (( ${#files[*]} )) ); then
-		bsdtar -c${TAR_OPT}f "$tempname" *
+		/bin/bsdtar -c${TAR_OPT}f "$tempname" *
 	else
 		# we have no packages remaining? zip up some emptyness
-		warning "$(gettext "No packages remain, creating empty database.")"
-		bsdtar -c${TAR_OPT}f "$tempname" -T /dev/null
+		warning "$(/bin/gettext "No packages remain, creating empty database.")"
+		/bin/bsdtar -c${TAR_OPT}f "$tempname" -T /dev/null
 	fi
 	popd >/dev/null
 
@@ -734,7 +734,7 @@ if (( success )); then
 			cp "$REPO_DB_FILE.sig" "$dblink.sig"
 	fi
 else
-	msg "$(gettext "No packages modified, nothing to do.")"
+	msg "$(/bin/gettext "No packages modified, nothing to do.")"
 	exit 1
 fi
 
